name: better_player_example
description: Better Player example usage app.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  better_player:
    path: ../
  flutter_localizations:
    sdk: flutter
  path_provider: any
  visibility_detector: any
  collection: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
  assets:
    - assets/
