name: better_player
description: Advanced video player based on video_player and Chewie. It's solves many typical use cases and it's easy to run.
version: 0.0.82
homepage: https://github.com/jhomlala/betterplayer
documentation: https://jhomlala.github.io/betterplayer/
publish_to: 'none'

environment:
  sdk: '>=2.16.2 <3.0.0'
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  wakelock: ^0.6.0+2
  meta: ^1.7.0
  flutter_widget_from_html_core: ^0.8.5+1
  visibility_detector: ^0.2.2
  path_provider: ^2.0.9
  collection: ^1.15.0
  xml: ^5.3.1
  volume:
    git:
      url: https://github.com/upvorg/Volume_Flutter.git
  screen_brightness: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_localizations:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.jhomlala.better_player
        pluginClass: BetterPlayerPlugin
      ios:
        pluginClass: BetterPlayerPlugin
